### ISSUE TITLE
add multi-precision integer arithmetic module

### ISSUE THREAD

**Issue by mycoboco** [mycoboco/ocelot#18]
A multi-precision integer arithmetic is necessary for `beluga` to support 64-bit integers.

Operations to implement signed/unsigned:
- [x] negation (#25)
- [x] addition (#19)
- [x] subtraction (#20)
- [x] multiplication (#21)
- [x] division (#22)
- [x] modulus (#23)
- [x] comparison (returns -1, 0 or 1) (#26)
- [x] bitwise and (#24)
- [x] bitwise or (#24)
- [x] bitwise xor (#24)
- [x] 1s' complement (#28)
- [x] left/right shift (arithmetic/logical) (#27)
- [x] conversion from/to native integers (#29)
- [x] conversion from/to strings (#30)
- [x] conversion from/to floating-points (#31)
- [x] documentation

**Comment by mycoboco** [comment]
The solutions given in the book is too generic. Use a double-word integer arithmetic for performance.

**Comment by mycoboco** [comment]
Operations to implement:
- [ ] negation
- [ ] addition
- [ ] subtraction
- [ ] multiplication
- [ ] division
- [ ] modulus
- [ ] comparison (returns -1, 0 or 1)
- [ ] bitwise and
- [ ] bitwise or
- [ ] bitwise xor
- [ ] 1s' complement
- [ ] left/right shift (arithmetic/logical)

**Comment by mycoboco** [comment]
Basic implementation has been done by f45d6033d562d462a85a6901a5cd8dd40ceb9afd and 7f5d8e05975ac97df4096ed732f61d3c5b66d7ed.
Word-array implementation (that work on little-endian machines like x86) has been added by 790bbaa93c411cb8450fed4010508f01aa696a88.
